---
esphome:
  name: blinds
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "IoT"
  domain: .thepromisedlan
  password: !secret iot_wifi_key

logger:

api:
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: office_blinds
            target: !lambda "return target;"

ota:

stepper:
  - platform: uln2003
    id: office_blinds
    pin_a: GPIO5
    pin_b: GPIO4
    pin_c: GPIO0
    pin_d: GPIO2
    max_speed: 1019 steps/s
    step_mode: FULL_STEP
    sleep_when_done: true
