---
esphome:
  name: office
  platform: ESP8266
  board: d1_mini
  includes:
    - "BSECSensor.h"
  libraries:
    - "BSEC Software Library"

wifi:
  ssid: "IoT"
  domain: .thepromisedlan
  password: !secret iot_wifi_key

logger:

api:

i2c:

ota:

sensor:
  - platform: custom
    lambda: |-
      auto bsec = new BSECSensor();
      App.register_component(bsec);
      return {
        bsec->temperatureSensor,
        bsec->pressureSensor,
        bsec->humiditySensor,
        bsec->airQualitySensor,
        bsec->gasResistanceSensor,
      };
    sensors:
      - name: "Office Temperature"
        unit_of_measurement: "°C"
        accuracy_decimals: 1
        icon: mdi:thermometer
      - name: "Office Pressure"
        unit_of_measurement: "Pa"
        accuracy_decimals: 1
        icon: mdi:gauge
      - name: "Office Humidity"
        unit_of_measurement: "%"
        accuracy_decimals: 1
        icon: mdi:water-percent
      - name: "Office Air Quality"
        unit_of_measurement: "IAQ"
        accuracy_decimals: 1
        icon: mdi:gauge
      - name: "Office Gas Resistance"
        unit_of_measurement: "Ω"
        accuracy_decimals: 1
        icon: mdi:gas-cylinder
