---
esphome:
  name: office
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "IoT"
  password: !secret iot_wifi_key

logger:

api:

i2c:

sensor:
  - platform: bme680
    address: 0x77
    update_interval: 30s
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
    humidity:
      id: hum
      name: "Office Humidity"
    gas_resistance:
      id: g_res
      name: "Office Gas Resistance"
  - platform: template
    name: "Office Air Quality"
    id: IAQ
    unit_of_measurement: IAQ
    lambda: "return log(id(g_res).state) + 0.04 * id(hum).state;"
