---
esphome:
  name: office
  platform: ESP8266
  board: d1_mini
  includes:
    - "CE_BSEC.h"
  libraries:
    - "BSEC Software Library"

wifi:
  ssid: "IoT"
  domain: .thepromisedlan
  password: !secret iot_wifi_key

logger:

api:

i2c:

ota:

sensor:
  - platform: custom
    lambda: |-
      auto IAQSensor = new CE_BSEC();
      App.register_component(IAQSensor);
      return {
        IAQSensor->TSensor,
        IAQSensor->PSensor,
        IAQSensor->HSensor,
        IAQSensor->AQSensor,
        IAQSensor->GRSensor,
      };
    sensors:
      - name: "Office Temperature"
        unit_of_measurement: "V"
        accuracy_decimals: 1
      - name: "Office Pressure"
        unit_of_measurement: "hPa"
        accuracy_decimals: 1
      - name: "Office Humidity"
        unit_of_measurement: "%"
        accuracy_decimals: 1
      - name: "Office Air Quality"
        unit_of_measurement: "IAQ"
        accuracy_decimals: 1
      - name: "Office Gas Resistance"
        unit_of_measurement: "Î©"
        accuracy_decimals: 1
