---
esphome:
  name: office
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "IoT"
  domain: .thepromisedlan
  password: !secret iot_wifi_key

logger:

api:

i2c:

ota:

bme680_bsec:
  address: 0x77

sensor:
  - platform: bme680_bsec
    temperature:
      name: "Office Temperature"
    pressure:
      name: "Office Pressure"
    humidity:
      name: "Office Humidity"
    gas_resistance:
      name: "Office Gas Resistance"
    iaq:
      name: "Office Air Quality"
    co2_equivalent:
      name: "Office CO2 Equivalent"
    breath_voc_equivalent:
      name: "Office Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "Office IAQ Accuracy"
